source 'https://rubygems.org'

group :jekyll_plugins do
    gem 'classifier-reborn', '2.3.0'
    gem 'jekyll', '4.3.4'
    gem 'jekyll-archives', '2.2.1'
    gem 'jekyll-email-protect', '1.1.0'
    gem 'jekyll-feed'
    gem 'jekyll-get-json', '1.0.0'
    gem 'jekyll-imagemagick', '1.4.0'
    gem 'jekyll-jupyter-notebook', '0.0.6'
    gem 'jekyll-link-attributes', '1.0.1'
    gem 'jekyll-minifier', '0.1.10'
    gem 'jekyll-paginate-v2', '3.0.0'
    gem 'jekyll-regex-replace', '1.1.0'
    gem 'jekyll-scholar', '7.1.3'
    gem 'jekyll-sitemap'
    gem 'jekyll-tabs', '1.2.1'
    gem 'jekyll-toc', '0.19.0'
    gem 'jekyll-twitter-plugin', '2.1.0'
    gem 'jemoji'
    gem 'unicode_utils', '1.4.0'
    gem 'webrick', '1.8.2'
    gem 'sass-embedded', '1.69.5'
    gem 'jekyll-sass-converter', '3.0.0'
end

group :other_plugins do
    gem 'css_parser', '1.19.1'
    gem 'feedjira', '3.2.3'
    gem 'httparty', '0.22.0'
end

group :dependencies do
    gem 'fast-stemmer', '1.0.2'
    gem 'i18n', '1.14.6'
    gem 'mercenary', '0.4.0'
    gem 'rouge', '4.4.0'
    gem 'terminal-table', '3.0.2'
    gem 'deep_merge', '1.2.2'
    gem 'cssminify2', '2.0.1'
    gem 'htmlcompressor', '0.4.0'
    gem 'json-minify', '0.0.3'
    gem 'uglifier', '4.2.1'
    gem 'bibtex-ruby', '6.1.0'
    gem 'citeproc-ruby', '1.1.14'
    gem 'csl-styles', '1.0.1.11'
    gem 'google-protobuf', '3.25.5'
    gem 'rake', '13.2.1'
    gem 'loofah', '2.22.0'
    gem 'sax-machine', '1.3.2'
    gem 'mini_mime', '1.1.5'
    gem 'multi_xml', '0.6.0'
    gem 'public_suffix', '6.0.1'
    gem 'concurrent-ruby', '1.3.4'
    gem 'rexml', '3.3.8'
    gem 'unicode-display_width', '2.6.0'
    gem 'json', '2.7.2'
    gem 'latex-decode', '0.4.0'
    gem 'citeproc', '1.0.10'
    gem 'csl', '1.6.0'
    gem 'activesupport', '7.1.5'
    gem 'crass', '1.0.6'
    gem 'namae', '1.2.0'
    gem 'benchmark', '0.4.0'
    gem 'logger', '1.6.1'
    gem 'minitest', '5.25.1'
    gem 'ffi', '1.17.0'
end
